
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

 

name: Node.js CI

 

on:

  workflow_dispatch:

jobs:

  webdriverio:

    runs-on: ubuntu-latest

 

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

 

    - name: Setup Node.js

      uses: actions/setup-node@v2

      with:

        node-version: 18.16.1

    - run: npm install

    - run: npm run build --if-present

    - run: npm run wdio

Building and testing Node.js - GitHub Docs

You can create a continuous integration (CI) workflow to build and test your Node.js project.